require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe DroneAttacksController do

  # This should return the minimal set of attributes required to create a valid
  # DroneAttack. As you add validations to DroneAttack, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end
  
  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # DroneAttacksController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all drone_attacks as @drone_attacks" do
      drone_attack = DroneAttack.create! valid_attributes
      get :index, {}, valid_session
      assigns(:drone_attacks).should eq([drone_attack])
    end
  end

  describe "GET show" do
    it "assigns the requested drone_attack as @drone_attack" do
      drone_attack = DroneAttack.create! valid_attributes
      get :show, {:id => drone_attack.to_param}, valid_session
      assigns(:drone_attack).should eq(drone_attack)
    end
  end

  describe "GET new" do
    it "assigns a new drone_attack as @drone_attack" do
      get :new, {}, valid_session
      assigns(:drone_attack).should be_a_new(DroneAttack)
    end
  end

  describe "GET edit" do
    it "assigns the requested drone_attack as @drone_attack" do
      drone_attack = DroneAttack.create! valid_attributes
      get :edit, {:id => drone_attack.to_param}, valid_session
      assigns(:drone_attack).should eq(drone_attack)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new DroneAttack" do
        expect {
          post :create, {:drone_attack => valid_attributes}, valid_session
        }.to change(DroneAttack, :count).by(1)
      end

      it "assigns a newly created drone_attack as @drone_attack" do
        post :create, {:drone_attack => valid_attributes}, valid_session
        assigns(:drone_attack).should be_a(DroneAttack)
        assigns(:drone_attack).should be_persisted
      end

      it "redirects to the created drone_attack" do
        post :create, {:drone_attack => valid_attributes}, valid_session
        response.should redirect_to(DroneAttack.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved drone_attack as @drone_attack" do
        # Trigger the behavior that occurs when invalid params are submitted
        DroneAttack.any_instance.stub(:save).and_return(false)
        post :create, {:drone_attack => {}}, valid_session
        assigns(:drone_attack).should be_a_new(DroneAttack)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        DroneAttack.any_instance.stub(:save).and_return(false)
        post :create, {:drone_attack => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested drone_attack" do
        drone_attack = DroneAttack.create! valid_attributes
        # Assuming there are no other drone_attacks in the database, this
        # specifies that the DroneAttack created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        DroneAttack.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => drone_attack.to_param, :drone_attack => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested drone_attack as @drone_attack" do
        drone_attack = DroneAttack.create! valid_attributes
        put :update, {:id => drone_attack.to_param, :drone_attack => valid_attributes}, valid_session
        assigns(:drone_attack).should eq(drone_attack)
      end

      it "redirects to the drone_attack" do
        drone_attack = DroneAttack.create! valid_attributes
        put :update, {:id => drone_attack.to_param, :drone_attack => valid_attributes}, valid_session
        response.should redirect_to(drone_attack)
      end
    end

    describe "with invalid params" do
      it "assigns the drone_attack as @drone_attack" do
        drone_attack = DroneAttack.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DroneAttack.any_instance.stub(:save).and_return(false)
        put :update, {:id => drone_attack.to_param, :drone_attack => {}}, valid_session
        assigns(:drone_attack).should eq(drone_attack)
      end

      it "re-renders the 'edit' template" do
        drone_attack = DroneAttack.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        DroneAttack.any_instance.stub(:save).and_return(false)
        put :update, {:id => drone_attack.to_param, :drone_attack => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested drone_attack" do
      drone_attack = DroneAttack.create! valid_attributes
      expect {
        delete :destroy, {:id => drone_attack.to_param}, valid_session
      }.to change(DroneAttack, :count).by(-1)
    end

    it "redirects to the drone_attacks list" do
      drone_attack = DroneAttack.create! valid_attributes
      delete :destroy, {:id => drone_attack.to_param}, valid_session
      response.should redirect_to(drone_attacks_url)
    end
  end

end
